// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eojxggczvdwujegqsgtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvanhnZ2N6dmR3dWplZ3FzZ3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTU3MDksImV4cCI6MjA2MTM3MTcwOX0.TBy_4CFg7J9roIsTcNuNdobcZO8SOMKnlR-_rr1aDj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);